import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const C = {
  navy:     rgb(0.106, 0.165, 0.290),
  gold:     rgb(0.788, 0.659, 0.298),
  white:    rgb(1, 1, 1),
  offwhite: rgb(0.973, 0.965, 0.949),
  accent:   rgb(0.945, 0.928, 0.875),
  muted:    rgb(0.42, 0.47, 0.55),
  dark:     rgb(0.12, 0.15, 0.20),
  light:    rgb(0.93, 0.94, 0.96),
  sage:     rgb(0.48, 0.63, 0.52),
};

function safe(text, max = 999) {
  return String(text || "").replace(/[^\x20-\x7E]/g, " ").trim().slice(0, max);
}

function wrap(text, maxChars = 75) {
  const words = safe(text, 600).split(/\s+/);
  const lines = []; let line = "";
  for (const w of words) {
    if ((line + " " + w).trim().length > maxChars) { if (line) lines.push(line.trim()); line = w; }
    else line = (line + " " + w).trim();
  }
  if (line) lines.push(line.trim());
  return lines.length ? lines : [""];
}

export async function buildPdfBuffer({ title, summary, deliverables = [], notes = [], callouts = [] }) {
  const pdf   = await PDFDocument.create();
  const font  = await pdf.embedFont(StandardFonts.Helvetica);
  const bold  = await pdf.embedFont(StandardFonts.HelveticaBold);

  const W = 612, H = 792, ML = 56, MR = 56, MT = 56;
  const CW = W - ML - MR;

  // ── Page factory ─────────────────────────────────────────────────────
  function newPage() {
    const p = pdf.addPage([W, H]);
    // Navy header
    p.drawRectangle({ x: 0, y: H - 48, width: W, height: 48, color: C.navy });
    // Gold left accent bar
    p.drawRectangle({ x: 0, y: 0, width: 6, height: H - 48, color: C.gold });
    // Brand text in header
    p.drawText("THE DIGITAL ATLAS", { x: ML, y: H - 31, size: 9.5, font: bold, color: C.gold });
    p.drawText("thedigitalatlas.vercel.app", { x: W - MR - 148, y: H - 31, size: 8.5, font, color: C.white });
    // Bottom footer
    p.drawRectangle({ x: 0, y: 0, width: W, height: 28, color: C.navy });
    p.drawText("AI-generated by The Digital Atlas  ·  Your personalised planning guide", {
      x: ML, y: 9, size: 7.5, font, color: rgb(0.5, 0.58, 0.7)
    });
    return { page: p, y: H - MT - 48 };
  }

  // ── Cursor helpers ────────────────────────────────────────────────────
  function drawText(ctx, text, x, y, size, f, color = C.dark) {
    ctx.page.drawText(safe(text, 120), { x, y, size, font: f, color });
  }
  function needsNewPage(ctx, needed = 80) {
    if (ctx.y < 40 + needed) { Object.assign(ctx, newPage()); }
  }

  // ── Page 1: Cover ────────────────────────────────────────────────────
  let ctx = newPage();

  // Hero block
  ctx.page.drawRectangle({ x: ML - 6, y: ctx.y - 108, width: CW + 12, height: 118, color: C.offwhite });
  ctx.page.drawRectangle({ x: ML - 6, y: ctx.y - 108, width: 5, height: 118, color: C.gold });

  // Title
  const titleLines = wrap(title, 38);
  let ty = ctx.y - 18;
  for (const line of titleLines.slice(0, 3)) {
    drawText(ctx, line, ML + 14, ty, 24, bold, C.navy);
    ty -= 30;
  }

  // Badge
  ctx.page.drawRectangle({ x: ML + 14, y: ctx.y - 116, width: 130, height: 19, color: C.gold });
  drawText(ctx, "DIGITAL PLANNING GUIDE", ML + 20, ctx.y - 112, 7.5, bold, C.navy);
  ctx.y -= 128;

  // Summary
  ctx.y -= 20;
  drawText(ctx, "About This Guide", ML, ctx.y, 12, bold, C.navy);
  ctx.y -= 8;
  ctx.page.drawRectangle({ x: ML, y: ctx.y, width: 44, height: 2.5, color: C.gold });
  ctx.y -= 18;
  for (const line of wrap(summary, 76).slice(0, 4)) {
    drawText(ctx, line, ML, ctx.y, 10.5, font, C.muted);
    ctx.y -= 15;
  }

  // What's inside box
  ctx.y -= 20;
  const boxItems = deliverables.filter(d => !d.startsWith("──")).slice(0, 10);
  const boxH = boxItems.length * 21 + 50;
  ctx.page.drawRectangle({ x: ML - 6, y: ctx.y - boxH, width: CW + 12, height: boxH, color: C.accent });
  ctx.y -= 8;
  drawText(ctx, "What's Inside This Guide", ML + 10, ctx.y, 12, bold, C.navy);
  ctx.y -= 20;
  for (const item of boxItems) {
    const lines = wrap(item, 66);
    ctx.page.drawRectangle({ x: ML + 10, y: ctx.y - 1, width: 7, height: 7, color: C.gold });
    drawText(ctx, lines[0] || "", ML + 26, ctx.y, 10, font, C.dark);
    ctx.y -= 19;
    for (const extra of lines.slice(1, 2)) {
      drawText(ctx, extra, ML + 26, ctx.y, 10, font, C.dark);
      ctx.y -= 16;
    }
  }

  // ── Pages 2+: Sections ────────────────────────────────────────────────
  ctx = newPage();

  // Section headings & items from deliverables
  let inSection = false;
  for (const item of deliverables) {
    needsNewPage(ctx, 60);
    if (item.startsWith("──")) {
      // Section heading
      ctx.y -= inSection ? 20 : 8;
      needsNewPage(ctx, 80);
      const heading = item.replace(/^──\s*/, "").trim();
      ctx.page.drawRectangle({ x: ML - 6, y: ctx.y - 6, width: CW + 12, height: 30, color: C.navy });
      drawText(ctx, heading, ML + 10, ctx.y + 2, 11.5, bold, C.gold);
      ctx.y -= 36;
      inSection = true;
    } else {
      // Regular bullet
      const lines = wrap(item, 70);
      // Gold bullet diamond
      ctx.page.drawRectangle({ x: ML + 10, y: ctx.y + 2, width: 6, height: 6, color: C.gold });
      drawText(ctx, lines[0] || "", ML + 24, ctx.y, 10.5, font, C.dark);
      ctx.y -= 17;
      for (const extra of lines.slice(1)) {
        drawText(ctx, extra, ML + 24, ctx.y, 10.5, font, C.dark);
        ctx.y -= 15;
      }
      ctx.y -= 4;
    }
  }

  // ── Timeline / notes page ─────────────────────────────────────────────
  if (notes.length) {
    ctx = newPage();
    drawText(ctx, "Your Step-by-Step Action Plan", ML, ctx.y, 14, bold, C.navy);
    ctx.y -= 10;
    ctx.page.drawRectangle({ x: ML, y: ctx.y, width: CW, height: 2.5, color: C.gold });
    ctx.y -= 22;

    for (const [i, note] of notes.entries()) {
      needsNewPage(ctx, 50);
      const lines = wrap(note, 68);
      // Numbered circle
      ctx.page.drawCircle({ x: ML + 11, y: ctx.y + 5, size: 10, color: C.navy });
      drawText(ctx, String(i + 1), ML + (i < 9 ? 8 : 6), ctx.y + 1, 8, bold, C.white);
      drawText(ctx, lines[0] || "", ML + 28, ctx.y, 10.5, font, C.dark);
      ctx.y -= 18;
      for (const extra of lines.slice(1)) {
        drawText(ctx, extra, ML + 28, ctx.y, 10.5, font, C.dark);
        ctx.y -= 15;
      }
      ctx.y -= 6;
    }
  }

  // ── CTA / next steps page ─────────────────────────────────────────────
  if (callouts.length) {
    ctx = newPage();

    // Gold accent box for heading
    ctx.page.drawRectangle({ x: ML - 6, y: ctx.y - 8, width: CW + 12, height: 36, color: C.accent });
    drawText(ctx, "Next Steps & Recommendations", ML + 10, ctx.y + 2, 13, bold, C.navy);
    ctx.y -= 46;

    for (const [i, cta] of callouts.entries()) {
      needsNewPage(ctx, 45);
      const lines = wrap(cta, 68);
      drawText(ctx, `${i + 1}.`, ML + 10, ctx.y, 11, bold, C.gold);
      drawText(ctx, lines[0] || "", ML + 28, ctx.y, 10.5, font, C.dark);
      ctx.y -= 18;
      for (const extra of lines.slice(1)) {
        drawText(ctx, extra, ML + 28, ctx.y, 10.5, font, C.dark);
        ctx.y -= 15;
      }
      ctx.y -= 8;
    }

    // CTA block
    needsNewPage(ctx, 100);
    ctx.y -= 24;
    ctx.page.drawRectangle({ x: ML - 6, y: ctx.y - 58, width: CW + 12, height: 78, color: C.navy });
    drawText(ctx, "Ready for the full editable bundle?", ML + 12, ctx.y, 13.5, bold, C.white);
    ctx.y -= 22;
    drawText(ctx, "Unlock the complete version: editable DOCX, pre-filled XLSX tracker,", ML + 12, ctx.y, 9.5, font, C.light);
    ctx.y -= 14;
    drawText(ctx, "and a print-ready PDF — all tailored to your exact goal.", ML + 12, ctx.y, 9.5, font, C.light);
    ctx.y -= 26;
    ctx.page.drawRectangle({ x: ML + 12, y: ctx.y - 4, width: 188, height: 24, color: C.gold });
    drawText(ctx, "thedigitalatlas.vercel.app", ML + 20, ctx.y + 3, 10, bold, C.navy);
  }

  return Buffer.from(await pdf.save());
}

// ── DOCX builder ─────────────────────────────────────────────────────────────
const crcTable = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
    t[n] = c >>> 0;
  }
  return t;
})();
function toBuffer(v) { return Buffer.isBuffer(v) ? v : Buffer.from(String(v || ""), "utf8"); }
function crc32(buf) { let c = 0xffffffff; for (const b of buf) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
function getDos(d = new Date()) {
  return { dosTime: (d.getUTCHours() << 11) | (d.getUTCMinutes() << 5) | Math.floor(d.getUTCSeconds() / 2), dosDate: ((Math.max(1980, d.getUTCFullYear()) - 1980) << 9) | ((d.getUTCMonth() + 1) << 5) | d.getUTCDate() };
}
function createZip(entries) {
  const localParts = [], centralParts = [];
  let offset = 0;
  for (const entry of entries) {
    const name = Buffer.from(entry.name, "utf8"), data = toBuffer(entry.data);
    const { dosDate, dosTime } = getDos(entry.date);
    const crc = crc32(data);
    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50,0); lh.writeUInt16LE(20,4); lh.writeUInt16LE(0,6);
    lh.writeUInt16LE(0,8); lh.writeUInt16LE(dosTime,10); lh.writeUInt16LE(dosDate,12);
    lh.writeUInt32LE(crc,14); lh.writeUInt32LE(data.length,18); lh.writeUInt32LE(data.length,22);
    lh.writeUInt16LE(name.length,26); lh.writeUInt16LE(0,28);
    localParts.push(lh, name, data);
    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50,0); ch.writeUInt16LE(20,4); ch.writeUInt16LE(20,6);
    ch.writeUInt16LE(0,8); ch.writeUInt16LE(0,10); ch.writeUInt16LE(dosTime,12);
    ch.writeUInt16LE(dosDate,14); ch.writeUInt32LE(crc,16); ch.writeUInt32LE(data.length,20);
    ch.writeUInt32LE(data.length,24); ch.writeUInt16LE(name.length,28); ch.writeUInt16LE(0,30);
    ch.writeUInt16LE(0,32); ch.writeUInt16LE(0,34); ch.writeUInt16LE(0,36);
    ch.writeUInt16LE(0,38); ch.writeUInt16LE(0,40); ch.writeUInt32LE(0x20,42);
    ch.writeUInt32LE(offset,42);
    centralParts.push(ch, name);
    offset += 30 + name.length + data.length;
  }
  const central = Buffer.concat(centralParts), eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50,0); eocd.writeUInt16LE(0,4); eocd.writeUInt16LE(0,6);
  eocd.writeUInt16LE(entries.length,8); eocd.writeUInt16LE(entries.length,10);
  eocd.writeUInt32LE(central.length,12); eocd.writeUInt32LE(offset,16); eocd.writeUInt16LE(0,20);
  return Buffer.concat([...localParts, central, eocd]);
}
function xe(v) {
  return String(v||"").replace(/[^\x20-\x7E\n\r\t]/g," ").trim()
    .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
    .replace(/"/g,"&quot;").replace(/'/g,"&apos;");
}
function wp(text, opts = {}) {
  const sz = opts.size || 22, color = opts.color || "1B2A4A";
  const b = opts.bold ? "<w:b/><w:bCs/>" : "";
  const shade = opts.shade ? `<w:shd w:val="clear" w:color="auto" w:fill="${opts.shade}"/>` : "";
  const spacing = `<w:spacing w:before="${opts.before||0}" w:after="${opts.after||120}"/>`;
  return `<w:p><w:pPr>${shade}${spacing}</w:pPr><w:r><w:rPr>${b}<w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:color w:val="${color}"/></w:rPr><w:t xml:space="preserve">${xe(text)}</w:t></w:r></w:p>`;
}
export function buildDocxBuffer({ title, summary, sections = [] }) {
  const body = [
    wp(title,   { size: 36, bold: true,  color: "1B2A4A", before: 0,   after: 80  }),
    wp(summary, { size: 21, color: "555F6F", before: 0, after: 200 }),
    ...sections.flatMap(s => [
      wp(s.heading, { size: 26, bold: true, color: "1B2A4A", shade: "F0ECD8", before: 280, after: 80 }),
      wp(s.body || "", { size: 20, color: "666666", before: 0, after: 80 }),
      ...(s.items || []).map(item => wp("• " + item, { size: 21, color: "333A45", before: 0, after: 80 }))
    ]),
    wp("Generated by The Digital Atlas — thedigitalatlas.vercel.app", { size: 16, color: "AAAAAA", before: 400, after: 0 })
  ].join("");
  return createZip([
    { name: "[Content_Types].xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>` },
    { name: "_rels/.rels", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>` },
    { name: "word/document.xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>` }
  ]);
}

// ── XLSX builder ──────────────────────────────────────────────────────────────
function buildWorksheetRows(rows) {
  return rows.map((row, ri) =>
    `<row r="${ri+1}">${row.map((cell, ci) =>
      `<c r="${String.fromCharCode(65+ci)}${ri+1}" t="inlineStr"><is><t>${xe(cell)}</t></is></c>`
    ).join("")}</row>`
  ).join("");
}
export function buildXlsxBuffer({ sheetName = "Plan", rows = [] }) {
  return createZip([
    { name: "[Content_Types].xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>` },
    { name: "_rels/.rels", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>` },
    { name: "xl/workbook.xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xe(sheetName)}" sheetId="1" r:id="rId1"/></sheets></workbook>` },
    { name: "xl/_rels/workbook.xml.rels", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>` },
    { name: "xl/worksheets/sheet1.xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${buildWorksheetRows(rows)}</sheetData></worksheet>` }
  ]);
}
